[package]
name = "rs-util"
version = "0.1.0"
edition = "2024"

[features]
arc_cow = []
async = ["dep:async-task"]
builder = []
cell = []
copy_on_write = []
deferred = []
id = ["dep:nohash-hasher", "dep:ahash"]
io = []
log = []
macros = []
option = []
puffin = ["dep:puffin"]
range = []
retainable = []
shared_string = []
toggle = []

all = [
    "arc_cow",
    "async",
    "builder",
    "cell",
    "copy_on_write",
    "deferred",
    "id",
    "io",
    "log",
    "macros",
    "option",
    "puffin",
    "range",
    "retainable",
    "shared_string",
    "toggle",
]
default = ["all"]


[dependencies]
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
derive_more = { version = "2.0.0", features = ["full"] }

parking_lot = "0.12"
async-task = { version = "4.7.1", optional = true }
nohash-hasher = { version = "0.2.0", optional = true }
ahash = { version = "0.8.12", optional = true }
rustc-hash = "2.1.1"
puffin = { version = "0.19.1", optional = true }


anyhow = "1.0.86"
rand = "0.9.1"
